/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#f9f9ff",
        surface: "#f9f9ff",
        "surface-tint": "#165ead",
        "on-surface": "#111c2d",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb786",
        "outline-variant": "#c2c6d3",
        "surface-container-highest": "#d8e3fb",
        primary: "#1e63b2",
        secondary: "#6e5e00",
        error: "#ba1a1a",
        "tertiary-fixed": "#ffdcc6",
        "surface-variant": "#d8e3fb",
        "surface-card": "#ffffff",
        "border-subtle": "#e2e8f0",
        "secondary-container": "#ffdf33",
        "on-secondary-container": "#726200",
        "surface-container-lowest": "#ffffff",
        outline: "#727782",
        "on-surface-variant": "#424751",
        "primary-fixed-dim": "#a7c8ff",
        "on-secondary-fixed-variant": "#534600",
        "primary-container": "#1e63b2",
        "secondary-fixed": "#fddd31",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#263143",
        "on-primary-fixed-variant": "#004789",
        "surface-dim": "#cfdaf2",
        "inverse-primary": "#a7c8ff",
        "on-secondary-fixed": "#211b00",
        "inverse-on-surface": "#ecf1ff",
        tertiary: "#783a00",
        "surface-container-high": "#dee8ff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#9c4d00",
        "surface-container-low": "#f0f3ff",
        "on-primary-fixed": "#001b3c",
        "on-tertiary-fixed-variant": "#723600",
        "secondary-fixed-dim": "#e4c50f",
        "primary-fixed": "#d5e3ff",
        "text-main": "#1e293b",
        "on-background": "#111c2d",
        "on-primary-container": "#d1e0ff",
        "on-primary": "#ffffff",
        "surface-bg": "#f8fafc",
        "on-tertiary-container": "#ffd8c0",
        "surface-container": "#e7eeff",
        "on-tertiary-fixed": "#311400",
        "surface-bright": "#f9f9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.75rem",
        "space-2xs": "0.25rem",
        "bottom-nav-height": "4.25rem",
        "sidebar-width": "16rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}